### ISSUE TITLE
Cannot add Omise, the package does not contain any assembly references or content files 

### ISSUE THREAD

**Issue by pebbo2la** [omise/omise-dotnet#18]
I tried to add Omise to my Project but it return me this error: 

Could not install package 'Omise 2.2.0.26558'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by chakrit** [comment]
@pebbo2la That error says that the library is not compatible with your project's target .NET framework settings.

Can you give me the version of Visual Studio and .NET framework that you are using?

**Comment by chakrit** [comment]
@pebbo2la I have ran some tests and found that in Silverlight or other PCL environments Visual Studio and NuGet seems to have a hard time figuring out the right combination of platforms.

I have uploaded tagged release for you here: https://github.com/omise/omise-dotnet/releases/tag/v2.2.0.26558 can you try downloading `Omise.zip` from there and use the DLLs inside instead of from NuGet? Let me know if this fixes it.

**Comment by chakrit** [comment]
Closing due to no communication.

@pebbo2la If you have move questions or this doesn't solve your problem please feel free to reopen the ticket or pop over to https://gitter.im/omise/omise-dotnet
